services:
  backend:
    profiles:
      - backend
    build:
      context: .
      target: backend_release
      dockerfile: Dockerfile
    working_dir: /
    ports:
      - "8000:8000"
    entrypoint:
      - ./start.sh

  postgres:
    profiles:
      - backend
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=my_django_app_project
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=my_secret_password

volumes:
  postgres_database:
